version: 0.0
os: linux
IgnoreApplicationStopFailures: true
files:
  - source: /
    destination: /var/www

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
